apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx-manifests
    repoURL: https://github.com/michael-dtit/argocd-demo.git
    targetRevision: HEAD