apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ quote .Values.namespace.name }}
data:
  {{- range $key, $value := .Values.conf_data }}
  {{$key}}:{{$value}}
  {{- end}}
